# 🧮 BÀI THỰC HÀNH: THƯ VIỆN NUMPY TRONG PYTHON

**Môn học:** Khoa học Dữ liệu / Lập trình Python  
**Thời gian:** 90 phút  
**Yêu cầu:** Python ≥ 3.8, NumPy ≥ 1.21

---

## 🎯 Mục tiêu bài thực hành

Sau khi hoàn thành bài thực hành này, sinh viên có thể:
- Tạo và thao tác với mảng NumPy (ndarray)
- Sử dụng các phép toán vector hóa (vectorized operations)
- Áp dụng indexing, slicing và broadcasting
- Thực hiện các phép tính thống kê và đại số tuyến tính cơ bản
- Giải quyết bài toán thực tế bằng NumPy

---
## ⚙️ PHẦN 0: Cài đặt và Import

In [1]:
# Cài đặt numpy nếu chưa có
# !pip install numpy

import numpy as np
print(f"✅ NumPy version: {np.__version__}")

✅ NumPy version: 2.3.5


---
## 📦 PHẦN 1: Tạo Mảng NumPy (ndarray)

### 1.1 Lý thuyết nhanh

NumPy cung cấp đối tượng `ndarray` (N-dimensional array) — mảng nhiều chiều hiệu năng cao.  
Khác với list Python, ndarray:
- Chứa **một kiểu dữ liệu duy nhất** (`dtype`)
- Hỗ trợ **vectorized operations** (không cần vòng lặp)
- Tốc độ **nhanh hơn nhiều lần** so với list thuần Python

In [2]:
# --- Tạo mảng từ list ---
a = np.array([1, 2, 3, 4, 5])
print("Mảng 1D:", a)
print("Shape:", a.shape, "| Dtype:", a.dtype, "| Ndim:", a.ndim)

# Mảng 2D
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print("\nMảng 2D:\n", b)
print("Shape:", b.shape)

Mảng 1D: [1 2 3 4 5]
Shape: (5,) | Dtype: int64 | Ndim: 1

Mảng 2D:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [3]:
# --- Các hàm tạo mảng đặc biệt ---
print("np.zeros(3,4):\n", np.zeros((3, 4)))
print("\nnp.ones(2,3):\n", np.ones((2, 3)))
print("\nnp.eye(4):\n", np.eye(4))
print("\nnp.arange(0,10,2):", np.arange(0, 10, 2))
print("\nnp.linspace(0,1,5):", np.linspace(0, 1, 5))

# Mảng ngẫu nhiên
np.random.seed(42)
rand_arr = np.random.randint(1, 100, size=(3, 4))
print("\nMảng ngẫu nhiên (3x4):\n", rand_arr)

np.zeros(3,4):
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

np.ones(2,3):
 [[1. 1. 1.]
 [1. 1. 1.]]

np.eye(4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

np.arange(0,10,2): [0 2 4 6 8]

np.linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]

Mảng ngẫu nhiên (3x4):
 [[52 93 15 72]
 [61 21 83 87]
 [75 75 88 24]]


### ✏️ Bài tập 1.1
Tạo các mảng sau:
1. Mảng 1D gồm 10 số lẻ đầu tiên (1, 3, 5, ..., 19)
2. Ma trận 4×4 với các phần tử ngẫu nhiên trong khoảng [-1.0, 1.0]
3. Ma trận đơn vị (identity) kích thước 5×5
4. Mảng 20 giá trị cách đều từ 0 đến π

In [4]:
# Viết code của bạn ở đây
# 1. Mảng 10 số lẻ đầu tiên
arr_odd = ...  # TODO
print("Số lẻ:", arr_odd)

# 2. Ma trận ngẫu nhiên [-1, 1]
arr_rand = ...  # TODO
print("\nNgẫu nhiên [-1,1]:\n", arr_rand)

# 3. Ma trận đơn vị 5x5
arr_eye = ...  # TODO
print("\nMa trận đơn vị:\n", arr_eye)

# 4. 20 giá trị từ 0 đến pi
arr_pi = ...  # TODO
print("\n0 → π:", arr_pi)

Số lẻ: Ellipsis

Ngẫu nhiên [-1,1]:
 Ellipsis

Ma trận đơn vị:
 Ellipsis

0 → π: Ellipsis


---
## 🔍 PHẦN 2: Indexing, Slicing và Reshaping

### 2.1 Indexing & Slicing

In [5]:
A = np.arange(1, 26).reshape(5, 5)
print("Ma trận A (5×5):\n", A)

print("\nPhần tử hàng 0, cột 2:", A[0, 2])
print("Hàng đầu tiên:", A[0, :])
print("Cột cuối:", A[:, -1])
print("Ma trận con 2×2 góc trên trái:\n", A[:2, :2])
print("Các hàng chẵn (0,2,4):\n", A[::2, :])

Ma trận A (5×5):
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Phần tử hàng 0, cột 2: 3
Hàng đầu tiên: [1 2 3 4 5]
Cột cuối: [ 5 10 15 20 25]
Ma trận con 2×2 góc trên trái:
 [[1 2]
 [6 7]]
Các hàng chẵn (0,2,4):
 [[ 1  2  3  4  5]
 [11 12 13 14 15]
 [21 22 23 24 25]]


In [6]:
# --- Boolean Indexing ---
print("Phần tử > 15:", A[A > 15])
print("Phần tử chẵn:\n", A[A % 2 == 0])

# Thay thế giá trị
B = A.copy()
B[B > 20] = 0
print("\nSau khi gán 0 cho phần tử > 20:\n", B)

Phần tử > 15: [16 17 18 19 20 21 22 23 24 25]
Phần tử chẵn:
 [ 2  4  6  8 10 12 14 16 18 20 22 24]

Sau khi gán 0 cho phần tử > 20:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [ 0  0  0  0  0]]


### ✏️ Bài tập 2.1
Cho ma trận `M = np.arange(1, 37).reshape(6, 6)`:
1. Lấy ma trận con 3×3 ở **góc dưới bên phải**
2. Lấy tất cả phần tử ở **hàng chẵn** và **cột lẻ**
3. Tìm tất cả phần tử **chia hết cho 3**
4. Thay tất cả phần tử **lớn hơn 30** bằng giá trị **-1**

In [7]:
M = np.arange(1, 37).reshape(6, 6)
print("Ma trận M:\n", M)

# 1. Ma trận con 3x3 góc dưới bên phải
sub_M = ...  # TODO
print("\n1. Góc dưới phải 3x3:\n", sub_M)

# 2. Hàng chẵn, cột lẻ (index bắt đầu từ 0)
even_odd = ...  # TODO
print("\n2. Hàng chẵn, cột lẻ:\n", even_odd)

# 3. Chia hết cho 3
div3 = ...  # TODO
print("\n3. Chia hết cho 3:", div3)

# 4. Thay phần tử > 30 bằng -1
M2 = M.copy()
# TODO
print("\n4. Sau khi thay:\n", M2)

Ma trận M:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

1. Góc dưới phải 3x3:
 Ellipsis

2. Hàng chẵn, cột lẻ:
 Ellipsis

3. Chia hết cho 3: Ellipsis

4. Sau khi thay:
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


---
## ⚡ PHẦN 3: Phép Toán Vectorized và Broadcasting

### 3.1 Phép toán element-wise

In [9]:
x = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
y = np.array([10.0, 20.0, 30.0, 40.0, 50.0])

print("x + y =", x + y)
print("x * y =", x * y)
print("x ** 2 =", x ** 2)
print("np.sqrt(y) =", np.sqrt(y))
print("np.log(x) =", np.log(x).round(4))
print("np.sin(x) =", np.sin(x).round(4))

x + y = [11. 22. 33. 44. 55.]
x * y = [ 10.  40.  90. 160. 250.]
x ** 2 = [ 1.  4.  9. 16. 25.]
np.sqrt(y) = [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]
np.log(x) = [0.     0.6931 1.0986 1.3863 1.6094]
np.sin(x) = [ 0.8415  0.9093  0.1411 -0.7568 -0.9589]


In [10]:
# --- Broadcasting ---
# NumPy tự động "mở rộng" mảng nhỏ để phù hợp mảng lớn

mat = np.ones((3, 4))
row_vec = np.array([1, 2, 3, 4])  # shape (4,)

print("ma trận (3,4) + vector (4,):\n", mat + row_vec)

col_vec = np.array([[10], [20], [30]])  # shape (3,1)
print("\nma trận (3,4) + cột (3,1):\n", mat + col_vec)

# Ứng dụng: chuẩn hóa dữ liệu
data = np.random.randint(1, 100, (4, 5)).astype(float)
data_norm = (data - data.mean(axis=0)) / data.std(axis=0)
print("\nDữ liệu gốc:\n", data)
print("\nChuẩn hóa (Z-score):\n", data_norm.round(3))

ma trận (3,4) + vector (4,):
 [[2. 3. 4. 5.]
 [2. 3. 4. 5.]
 [2. 3. 4. 5.]]

ma trận (3,4) + cột (3,1):
 [[11. 11. 11. 11.]
 [21. 21. 21. 21.]
 [31. 31. 31. 31.]]

Dữ liệu gốc:
 [[ 3. 22. 53.  2. 88.]
 [30. 38.  2. 64. 60.]
 [21. 33. 76. 58. 22.]
 [89. 49. 91. 59. 42.]]

Chuẩn hóa (Z-score):
 [[-1.016 -1.391 -0.074 -1.725  1.442]
 [-0.178  0.258 -1.586  0.72   0.288]
 [-0.457 -0.258  0.608  0.483 -1.277]
 [ 1.651  1.391  1.053  0.522 -0.453]]


### ✏️ Bài tập 3.1 — Chuyển đổi nhiệt độ

Cho mảng nhiệt độ (°C) của 7 ngày trong tuần:  
`temps_c = [28.5, 30.1, 29.8, 31.2, 27.6, 26.9, 30.5]`

Sử dụng NumPy (không dùng vòng lặp) để:
1. Chuyển sang **°F** (công thức: F = C × 9/5 + 32)
2. Chuyển sang **Kelvin** (K = C + 273.15)
3. Tìm nhiệt độ **trung bình**, **cao nhất**, **thấp nhất**
4. Tìm **ngày** (index) có nhiệt độ cao nhất và thấp nhất

In [11]:
temps_c = np.array([28.5, 30.1, 29.8, 31.2, 27.6, 26.9, 30.5])
days = ['Thứ 2', 'Thứ 3', 'Thứ 4', 'Thứ 5', 'Thứ 6', 'Thứ 7', 'Chủ nhật']

# 1. °F
temps_f = ...  # TODO
print("°F:", temps_f)

# 2. Kelvin
temps_k = ...  # TODO
print("Kelvin:", temps_k)

# 3. Thống kê
mean_t = ...  # TODO
max_t  = ...  # TODO
min_t  = ...  # TODO
print(f"\nTrung bình: {mean_t:.2f}°C | Cao nhất: {max_t}°C | Thấp nhất: {min_t}°C")

# 4. Ngày
idx_max = ...  # TODO
idx_min = ...  # TODO
print(f"Nóng nhất: {days[idx_max]} | Mát nhất: {days[idx_min]}")

°F: Ellipsis
Kelvin: Ellipsis


TypeError: unsupported format string passed to ellipsis.__format__

---
## 📊 PHẦN 4: Thống Kê và Đại Số Tuyến Tính

In [13]:
# Giả lập điểm thi của 5 sinh viên, 4 môn học
np.random.seed(0)
scores = np.random.randint(5, 10, size=(5, 4)).astype(float)
subjects = ['Toán', 'Lý', 'Hóa', 'Văn']
students = ['SV1', 'SV2', 'SV3', 'SV4', 'SV5']

print("Bảng điểm:")
print(f"{'':6}", *[f"{s:6}" for s in subjects])
for i, sv in enumerate(students):
    print(f"{sv:6}", *[f"{scores[i,j]:6.1f}" for j in range(4)])

print("\n--- Thống kê theo từng môn (axis=0) ---")
print("Trung bình:", scores.mean(axis=0).round(2))
print("Cao nhất:  ", scores.max(axis=0))
print("Thấp nhất: ", scores.min(axis=0))
print("Độ lệch chuẩn:", scores.std(axis=0).round(2))

print("\n--- Điểm trung bình mỗi sinh viên (axis=1) ---")
for i, sv in enumerate(students):
    print(f"{sv}: {scores[i].mean():.2f}")

Bảng điểm:
       Toán   Lý     Hóa    Văn   
SV1       9.0    5.0    8.0    8.0
SV2       8.0    6.0    8.0    7.0
SV3       9.0    5.0    5.0    9.0
SV4       7.0    6.0    5.0    6.0
SV5       6.0    5.0    6.0    9.0

--- Thống kê theo từng môn (axis=0) ---
Trung bình: [7.8 5.4 6.4 7.8]
Cao nhất:   [9. 6. 8. 9.]
Thấp nhất:  [6. 5. 5. 6.]
Độ lệch chuẩn: [1.17 0.49 1.36 1.17]

--- Điểm trung bình mỗi sinh viên (axis=1) ---
SV1: 7.50
SV2: 7.25
SV3: 7.00
SV4: 6.00
SV5: 6.50


In [ ]:
# --- Đại số tuyến tính ---
A = np.array([[2, 1, -1],
              [-3, -1, 2],
              [-2, 1, 2]], dtype=float)
b_vec = np.array([8, -11, -3], dtype=float)

print("Ma trận A:\n", A)
print("\nVế phải b:", b_vec)
print("\nĐịnh thức det(A):", round(np.linalg.det(A), 4))
print("\nNghịch đảo A^(-1):\n", np.linalg.inv(A).round(4))

# Giải hệ phương trình tuyến tính Ax = b
x_sol = np.linalg.solve(A, b_vec)
print("\nNghiệm x =", x_sol)
print("Kiểm tra A·x =", A @ x_sol)  # phải bằng b_vec

### ✏️ Bài tập 4.1 — Phân tích điểm thi

Sử dụng bảng `scores` ở trên:
1. Xếp hạng sinh viên theo điểm trung bình (cao → thấp)
2. Sinh viên nào đạt điểm **≥ 8** ở **tất cả** các môn?
3. Tính **ma trận tương quan** giữa 4 môn học
4. Môn nào có điểm số **biến động lớn nhất** (độ lệch chuẩn cao nhất)?

In [ ]:
# 1. Xếp hạng theo điểm trung bình
avg_scores = scores.mean(axis=1)
rank_idx = ...  # TODO: dùng np.argsort
print("Xếp hạng:")
for rank, idx in enumerate(rank_idx, 1):
    print(f"  Hạng {rank}: {students[idx]} ({avg_scores[idx]:.2f})")

# 2. Sinh viên đạt >= 8 tất cả môn
all_good = ...  # TODO
print("\nSV đạt ≥ 8 tất cả môn:", [students[i] for i in range(5) if all_good[i]])

# 3. Ma trận tương quan
corr = ...  # TODO: dùng np.corrcoef
print("\nMa trận tương quan:\n", corr.round(3))

# 4. Môn biến động nhất
std_scores = scores.std(axis=0)
most_varied = ...  # TODO
print(f"\nMôn biến động nhất: {subjects[most_varied]} (std={std_scores[most_varied]:.3f})")

---
## 🚀 PHẦN 5: Bài Toán Tổng Hợp — Phân Tích Dữ Liệu Bán Hàng

Công ty có **5 sản phẩm**, bán tại **4 khu vực**, trong **12 tháng**.  
Dữ liệu gồm: số lượng bán (units) và đơn giá (nghìn đồng).

In [ ]:
np.random.seed(99)

products = ['Laptop', 'Điện thoại', 'Tablet', 'Tai nghe', 'Chuột']
regions  = ['Hà Nội', 'HCM', 'Đà Nẵng', 'Cần Thơ']
months   = [f'T{m}' for m in range(1, 13)]

# units[product, region, month]
units = np.random.randint(10, 200, size=(5, 4, 12))

# Giá (nghìn đồng)
prices = np.array([15000, 8000, 6000, 800, 300])  # shape (5,)

# Doanh thu = units * price cho mỗi sản phẩm
# prices phải có shape (5,1,1) để broadcast với units (5,4,12)
revenue = units * prices[:, np.newaxis, np.newaxis]

print(f"Shape units: {units.shape}")
print(f"Shape revenue: {revenue.shape}")
print(f"Tổng doanh thu toàn công ty: {revenue.sum():,} nghìn đồng")

### ✏️ Bài tập 5.1 — Phân tích kinh doanh

Sử dụng mảng `units`, `prices`, `revenue`:

1. Doanh thu **mỗi sản phẩm** (tổng theo tất cả khu vực và tháng)
2. Doanh thu **mỗi khu vực** (tổng theo tất cả sản phẩm và tháng)
3. Doanh thu **mỗi tháng** (tổng theo tất cả sản phẩm và khu vực) — nhận xét xu hướng
4. Sản phẩm **bán chạy nhất** (theo số lượng) tại **mỗi khu vực**
5. Tháng nào có **doanh thu cao nhất** và **thấp nhất**?

In [ ]:
# 1. Doanh thu mỗi sản phẩm
rev_by_product = ...  # TODO: sum theo axis (1,2)
print("1. Doanh thu theo sản phẩm (nghìn đồng):")
for i, p in enumerate(products):
    print(f"   {p}: {rev_by_product[i]:>12,}")

# 2. Doanh thu mỗi khu vực
rev_by_region = ...  # TODO: sum theo axis (0,2)
print("\n2. Doanh thu theo khu vực (nghìn đồng):")
for i, r in enumerate(regions):
    print(f"   {r}: {rev_by_region[i]:>12,}")

# 3. Doanh thu mỗi tháng
rev_by_month = ...  # TODO: sum theo axis (0,1)
print("\n3. Doanh thu theo tháng:")
for i, m in enumerate(months):
    print(f"   {m}: {rev_by_month[i]:>12,}")

# 4. Sản phẩm bán chạy nhất theo khu vực
# units_by_product_region: sum theo tháng → shape (5, 4)
units_pr = ...  # TODO
best_product_per_region = ...  # TODO: argmax theo axis 0
print("\n4. Sản phẩm bán chạy nhất tại mỗi khu vực:")
for i, r in enumerate(regions):
    print(f"   {r}: {products[best_product_per_region[i]]}")

# 5. Tháng doanh thu cao/thấp nhất
best_month  = ...  # TODO
worst_month = ...  # TODO
print(f"\n5. Tháng cao nhất: {months[best_month]} | Thấp nhất: {months[worst_month]}")

---
## ⭐ PHẦN 6 (BONUS): Hiệu Năng NumPy vs Python thuần

Minh họa tốc độ vượt trội của NumPy.

In [ ]:
import time

N = 1_000_000

# Python thuần
py_list = list(range(N))
t0 = time.time()
result_py = sum(x**2 for x in py_list)
t_py = time.time() - t0

# NumPy
np_arr = np.arange(N)
t0 = time.time()
result_np = (np_arr ** 2).sum()
t_np = time.time() - t0

print(f"Python list: {t_py*1000:.1f} ms")
print(f"NumPy array: {t_np*1000:.1f} ms")
print(f"🚀 NumPy nhanh hơn {t_py/t_np:.0f}x!")
print(f"Kết quả giống nhau: {result_py == result_np}")

---
## 📝 Tổng Kết và Nộp Bài

| Phần | Nội dung | Điểm |
|------|----------|------|
| 1.1  | Tạo mảng NumPy | 1.5đ |
| 2.1  | Indexing & Slicing | 2.0đ |
| 3.1  | Vectorized operations | 2.0đ |
| 4.1  | Thống kê | 2.0đ |
| 5.1  | Bài toán tổng hợp | 2.5đ |
| **Tổng** | | **10đ** |

### 🔗 Tài liệu tham khảo
- [NumPy Official Docs](https://numpy.org/doc/stable/)
- [NumPy Cheat Sheet](https://numpy.org/doc/stable/user/quickstart.html)
- [Broadcasting Rules](https://numpy.org/doc/stable/user/basics.broadcasting.html)

---
> **Lưu ý:** Chạy tất cả các ô code trước khi nộp. Đảm bảo không có lỗi (error) nào.